---
Name: nswdpc-memberprofile-extensions
Only:
  moduleexists: 'nswdpc/silverstripe-members'
---
NSWDPC\Members\MemberController:
  extensions:
    # apply theme requirements
    - 'NSWDPC\Waratah\Extensions\DesignSystemAssetExtension'
    # apply search extension (for global search form)
    - 'nglasl\extensible\ExtensibleSearchExtension'
NSWDPC\Members\MemberProfileController:
  extensions:
    # apply theme requirements
    - 'NSWDPC\Waratah\Extensions\DesignSystemAssetExtension'
    # apply search extension (for global search form)
    - 'nglasl\extensible\ExtensibleSearchExtension'
