---
Name: nswdpc-memberprofile-extensions
Only:
  moduleexists: 'nswdpc/silverstripe-members'
---
NSWDPC\Members\MemberController:
  extensions:
    - 'NSWDPC\Waratah\Extensions\DesignSystemAssetExtension'
NSWDPC\Members\MemberProfileController:
  extensions:
    # apply theme requirements
    - 'NSWDPC\Waratah\Extensions\DesignSystemAssetExtension'
